# Generated by Django 5.2.4 on 2025-07-21 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "book_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "case_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.TextField(max_length=30)),
                ("form_factor", models.TextField(max_length=15)),
                ("color", models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Cpu",
            fields=[
                (
                    "cpu_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.TextField(max_length=30)),
                ("core_count", models.IntegerField()),
                ("base_clock_speed", models.FloatField()),
                ("socket_type", models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Gpu",
            fields=[
                (
                    "gpu_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.TextField(max_length=30)),
                ("memory_size", models.IntegerField()),
                ("chipset", models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                (
                    "motherboard_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.TextField(max_length=30)),
                ("socket_type", models.TextField(max_length=15)),
                ("ram_slots", models.IntegerField()),
                ("max_ram", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PowerSupply",
            fields=[
                (
                    "psu_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.TextField(max_length=30)),
                ("wattage", models.IntegerField()),
                ("certification", models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Ram",
            fields=[
                (
                    "ram_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("part_number", models.TextField(max_length=20)),
                ("brand_name", models.TextField(max_length=20)),
                ("ram_name", models.TextField(max_length=10)),
                ("capacity", models.IntegerField()),
                ("ddr", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "storage_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.TextField(max_length=30)),
                ("capacity", models.IntegerField()),
                ("storage_type", models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Choise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "computer_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("computer_name", models.CharField(max_length=200, unique=True)),
                (
                    "computer_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.case"
                    ),
                ),
                (
                    "computer_cpu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.cpu"
                    ),
                ),
                (
                    "computer_gpu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.gpu"
                    ),
                ),
                (
                    "computer_psu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.powersupply",
                    ),
                ),
                (
                    "computer_ram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.ram"
                    ),
                ),
                (
                    "computer_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.storage"
                    ),
                ),
            ],
        ),
    ]
