# Generated by Django 5.2.4 on 2025-07-20 05:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_person_person_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
